const shirts = [
    {
        id: 1,
        image: "https://m.media-amazon.com/images/I/614XQNFR2ML._AC_UY1100_.jpg",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },
    {
        id: 2,
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/shirt/u/o/q/xl-glp-04-fronics-original-imags8pjkebunutg.jpeg?q=90&crop=false",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },
    {
        id: 3,
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/shirt/p/4/4/s-mf001-mineza-original-imagfygr7b5qrh3z.jpeg?q=20&crop=false",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },    
    {
        id: 4,
        image: "https://m.media-amazon.com/images/I/41dwFub9-XL._AC_UY1100_DpWeblab_.jpg",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },    
    {
        id: 5,
        image: "https://5.imimg.com/data5/SELLER/Default/2022/9/LY/AW/PB/98564971/denim-shirt-500x500.jpeg",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },    
    {
        id: 6,
        image: "https://img3.junaroad.com/uiproducts/19672306/pri_175_p-1680963103.jpg",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },    
    {
        id: 7,
        image: "https://rukminim2.flixcart.com/image/850/1000/knunf680/shirt/p/k/o/xxl-c442-olive-dennis-lingo-original-imag2fp7s6dytdxf.jpeg?q=20&crop=false",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },    
    {
        id: 8,
        image: "https://img3.junaroad.com/uiproducts/20406564/std_300_1-1697159949.jpg",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },     
    {
        id: 9,
        image: "https://assets2.andaazfashion.com/media/catalog/product/cache/1/image/800x1200/a12781a7f2ccb3d663f7fd01e1bd2e4e/o/f/off-white-silk-jacket-style-mens-kurta-with-churidar-mkpa02119-1.jpg",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },     
    {
        id: 10,
        image: "https://media.nihalfashions.com/media/catalog/product/cache/caa15edf98145413286703527de7b8dd/b/r/brown-cotton-mens-kurta-pajama-nmk-6125.jpg",
        brand: "Casual Shirt",
        discountPercent: 70,
        discountPrice: 200,
        price: 2000,
        title: "Lorem ipsum dolor sit elit. Quisquam, quia.",
    },     
]

export default shirts